<form action="consulta_nome_animal.php" method="POST">
    <center><h3 class="transf">Informe os dados baixo:</h3></center>
    <div class=" container alinhar">
        <div class="form-row">
            <div class="form-group col-md-12">
                <label>Pesquise o nome do animal</label>
                <input type="text" class="form-control" name="nome">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Consultar</button>
        <a class="btn btn-primary" href="index.php" role="button">Voltar</a>
    </div>
</form>