<main class="bd-masthead" id="content" role="main">
    <div class="container">
        <div class="row">
            <div class="col-5 mx-auto col-md-5 order-md-1 imagem">
                <img src="img/mapa.png" width="370" height="340" class="img-fluid mb-3 mb-md-0" focusable="false" role="img"></img>
            </div>
            <div class="col-md-7 order-md-2 text-center text-md-center pr-md-8 texto_inicial_2">
                <h1 class="mb-3">Pet-shop MANIA!</h1>
                <p class="lead mb-4">
                    Para lhe ajudar a navegar, mostramos algumas opções.
                </p>
                <a class="btn btn-primary" href="cadastro_animal.php" role="button">Cadastro de Animal</a>
                <a class="btn btn-primary" href="consulta_animal.php" role="button">Consulta de Animal</a>
                <a class="btn btn-primary" href="consulta_nome_animal.php" role="button">Consulta de Animal por Nome</a>
            </div>
        </div>
    </div>
</main>
